const ActionTypes = {
  MODALS: {
    SHOW_EDIT_MODAL: "SHOW_EDIT_MODAL",
    CLOSE_EDIT_MODAL: "CLOSE_EDIT_MODA",
    SHOW_VIEW_MODAL: "SHOW_VIEW_MODAL",
    CLOSE_VIEW_MODAL: "CLOSE_VIEW_MODAL",
    SHOW_PAYMENT_EDIT_MODAL: "SHOW_PAYMENT_EDIT_MODAL",
    CLOSE_PAYMENT_EDIT_MODAL: "CLOSE_PAYMENT_EDIT_MODAL",
    SHOW_PAYMENT_CREATE_MODAL: "SHOW_PAYMENT_CREATE_MODAL",
    CLOSE_PAYMENT_CREATE_MODAL: "CLOSE_PAYMENT_CREATE_MODAL",
  },
};

export default ActionTypes;
