const ActionTypes = {
  MODALS: {
    SHOW_EDIT_MODAL: "SHOW_EDIT_MODAL",
    CLOSE_EDIT_MODAL: "CLOSE_EDIT_MODA",
    SHOW_VIEW_MODAL: "SHOW_VIEW_MODAL",
    CLOSE_VIEW_MODAL: "CLOSE_VIEW_MODAL",
    SHOW_DELETE_MODAL: "SHOW_DELETE_MODAL",
    CLOSE_DELETE_MODAL: "CLOSE_DELETE_MODAL",
    SHOW_PAYMENT_EDIT_MODAL: "SHOW_PAYMENT_EDIT_MODAL",
    CLOSE_PAYMENT_EDIT_MODAL: "CLOSE_PAYMENT_EDIT_MODAL",
    SHOW_PAYMENT_CREATE_MODAL: "SHOW_PAYMENT_CREATE_MODAL",
    CLOSE_PAYMENT_CREATE_MODAL: "CLOSE_PAYMENT_CREATE_MODAL",
    SHOW_BANNER_VIEW_MODAL: "SHOW_BANNER_VIEW_MODAL",
    CLOSE_BANNER_VIEW_MODAL: "CLOSE_BANNER_VIEW_MODAL",
    SHOW_ORDER_EDIT_MODAL: "SHOW_ORDER_EDIT_MODAL",
    CLOSE_ORDER_EDIT_MODAL: "CLOSE_ORDER_EDIT_MODAL",
  },
  AUTH: {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SET_USER: "SET_USER",
    SET_USER_ERROR: "SET_USER_ERROR",
    SET_USER_LOADING: "SET_USER_LOADING",
    SET_USER_SUCCESS: "SET_USER_SUCCESS",
    SET_USER_PHONE: "SET_USER_PHONE",
  },
};

export default ActionTypes;
